### ISSUE TITLE
Welcome to SEBC!

### ISSUE THREAD

**Issue by mfernest** [ibrahimsaf/SEBC#2]
Please note your repo has a redundant top-level directory. This extra layer defeats any automated checking we might perform when working through 16 repositories at a time.

Please reconfigure the repository so that the working folders -- installation, storage, resources, etc., appear at the top level.

Please also comment with your full name here so we can make sure of a match between your GitHub handle and registered name.

Regards,

Rob & Michael

**Comment by ibrahimsaf** [comment]
Hello,
The organisation is modified.
My Name is "Ibrahim Safieddine".
Regards
Ibrahim

**Comment by mfernest** [comment]
Thanks. Appreciate the repo name change to "SEBC" as well.
